@startuml
'https://plantuml.com/sequence-diagram


Ant -> Mediator : isPredatorNearby
Mediator -> Ant : hasFoundPredator
Ant -> Mediator : handleFoundPredator
Mediator -> Soldier : goFight
Mediator -> Ant2 : flee

@enduml