@startuml
'https://plantuml.com/sequence-diagram
'not used
autonumber

Resource -> Mediator : checkForNearbyScouts
Mediator -> Scout : hasFoundResource
Scout -> Mediator : handleResourceFound
Mediator -> Gatherer : goToObjective

@enduml