@startuml
'https://plantuml.com/sequence-diagram

autonumber

Scout -> Mediator : update
Mediator -> Scout : handleScoutUpdate
Scout -> Mediator : areThereResourcesNearby
Mediator -> Scout : position
loop for each resource
    Mediator -> Resource : position
end

alt resource within range
    Mediator -> Mediator : addToFoundResources
    loop for each unit of food in the resource
        Mediator -> Gatherer : setObjective to the resource
    end
end

@enduml