@startuml
'https://plantuml.com/sequence-diagram

autonumber

Predator -> Mediator : isPreyNearby
Mediator -> Predator : hasFoundPrey
Predator -> Mediator : attackPrey
Mediator -> Ant : youDie
Ant -> Mediator : inDeedImDead

@enduml